### ISSUE TITLE
Load FAM tables with Load FOM Keycloak data

### ISSUE THREAD

**Issue by ianliuwk1019** [bcgov/nr-forests-access-management#104]
As a Developer, I want to retrieve existing FOM Keycloak user data, ~so that I can insert the data into FAM.~ and load it into the FAM database through the `user_role_assignment` end point.

- Use the keycloak API to read all the existing FOM role assignments
- For each existing role assignment, add a role assignment in FAM by calling the FAM API (simpler than generating SQL because the endpoint has a bunch of logic that we would have had to replicate)
- Need to pass in a JWT to the FAM API to get through security checks
- If any users are not already in FAM, they should get added when the role assignment endpoint is called (already implemented)
- If any forest client is not already in FAM, it should get added when the role assignment endpoint is called 
- If the forest client role is not already in FAM, it should get added when the role assignment endpoint is called (already implemented)

API changes required for this ticket:

- [x] Make role purpose optional (forest client roles don't need it -- the parent role describes the purpose) -- implemented as part of PR #384
- [x] Remove the "name" field from the forest client table (we don't have the name and we're not using the data and it won't stay synchronized with FC anyway. Putting in a "dummy" name is dumb. In the future, anyone that needs the name can call the FC API to get the correct name) -- done in PR #340
- [x] Add logic to the role assignment endpoint so that the forest client record is created if necessary -- done in PR #360

### Kevin's rough Role Assignment notes for history:
* if the role specified for the assignment is Abstract, and a forest client id is specified, a new role child role is automatically created with "prefix"_"forest_client_number" where:
  * prefix = `<name of parent role>`
  * if parent role (abstract) is   `FOM-Submitter` and the forest client number is `00001101` then the new role will be: `FOM-Submitter_00001101`
* the role_purpose for the new child role will be left blank **Make role purpose optional**
  
* A new forest client record is created in the database:
  * forest client name:   "DUMMY_FOREST_CLIENT_NAME_00001102" ***(Planning to drop the Forest Client  Name column)

**Comment by ArogeG** [comment]
@franTarkenton, thanks for working on this. Please can you drop a comment on where you got to with this ticket and what is outstanding. I'm sure you already explained this on one of the scrum calls. Thank you!

**Comment by franTarkenton** [comment]
Hey @ArogeG This ticket is complete.  The script will migrate users and roles from keycloak to FAM.   Changes will be required to get the script to work once the work to secure the API is complete.  The script uses the POST / roles end point to create the roles.  Once the roles are created the users are added using the role assignment end point.  This logic was used because the role assignment end point does not support creating child role.

**Comment by ConradBoydElliottGustafson** [comment]
@franTarkenton Where is the actual script? I can't find it in the repo. Is this in another repo?

**Comment by ConradBoydElliottGustafson** [comment]
Pete found it here: https://github.com/bcgov/nr-forests-access-management/tree/feat/104-kc-data-load-scripts/scripts/kc_data_transfer

Kevin passed me all the values for the environment variables, so UNBLOCKED

**Comment by ConradBoydElliottGustafson** [comment]
Restored the database from snapshot, changed the name in the prod terraform file and tried doing a restore. Got an error:Error: deleting RDS Subnet Group (prod-fam-cluster-subnet-group): InvalidDBSubnetGroupStateFault: Cannot delete the subnet group 'prod-fam-cluster-subnet-group' because at least one database instance: prod-fam-cluster-restore is still using it.

**Comment by ConradBoydElliottGustafson** [comment]
Probably a good idea to remove the old DB + DB subnet group from terraform state before re-running the Terraform apply. Figuring it out.

**Comment by ArogeG** [comment]
@ConradBoydElliottGustafson I have gone through the records from the script and found that they correspond with the users listed in the FOM Soft Launch spreadsheet. If there is no further action required from your side,  I am ready to close this task.
