### ISSUE TITLE
Delegate Admin epic design

### ISSUE THREAD

**Issue by gormless87** [bcgov/nr-forests-access-management#1124]
Update the [Delegated Access Administration Design](https://apps.nrs.gov.bc.ca/int/confluence/x/VoC9CQ) Confluence page to reflect current status 

Acceptance Criteria:
- [ ] User story breakdown tables are up-to-date
- [ ] Tasks are described
- [ ] Tasks associated with a GH issue where possible

**Comment by basilv** [comment]
https://apps.nrs.gov.bc.ca/int/confluence/display/FSAST1/Delegated+Access+Administration+Design
