### ISSUE TITLE
Validate BCeID as a BCeID user

### ISSUE THREAD

**Issue by OlgaLiber2** [bcgov/nr-forests-access-management#1181]
**Describe the task**
As a BCeID user (i.e. delegated admin) I want to be able to validate BCeID users when granting access just like existing IDIR admins

**Acceptance Criteria**
- [x] Understand whether code changes are required based on validating BCeID user like IDIR validation (create a new ticket if code changes are required)
- [x] Ensure IDIM service agreement allows for these scenarios, if changes are required send email to IDIM Consulting regarding required updates to IDIM service agreement

**Additional context**

**Comment by basilv** [comment]
Need BCeID lookup by user GUID for backend.
Need BCeID lookup by user name for frontend.

**Comment by MCatherine1994** [comment]
IDIR lookup BCEID by userGUID is not enabled in production, we need that to be enabled.

The "searchInternalAccount" method for searching IDIR user doesn't seem to support lookup IDIR by userGUID

**Comment by ianliuwk1019** [comment]
For "**GetAccountDetail**" which is used for **BCeID** user to look up **BCeID users** using **GUID**, as of today (**May 3rd**) that I can see it does not seem to be even enabled in **TEST environment.**
requester user_guid ("BDA2A1E212244DC2B9F9522057C58BBB"): **TEST-3-LOAD-CHILD-1**
look up BCeID user by guid ("E7C0431DA55D4ACA9FA901EE2C91CB3B"): **LOAD-3-TEST**
"""
		businessBceid?
		searchUserBy=**userGuid**
		&searchValue=**E7C0431DA55D4ACA9FA901EE2C91CB3B**
		&**requesterUserGuid**=**BDA2A1E212244DC2B9F9522057C58BBB**
		&requesterAccountTypeCode=Business
		API result: {**'found': False**, 'guid': 'E7C0431DA55D4ACA9FA901EE2C91CB3B'}
"""
May the 4th be ready?
@MCatherine1994 @OlgaLiber2

**Comment by MCatherine1994** [comment]
bceid lookup for self is not enabled, not sure if we'll have the case a user try to search for himself

**Comment by MCatherine1994** [comment]
Frontend: 
- [ ] IDIR lookup IDIR by userID  (scenario 4.3a, 4.3b is enabled in TEST and PROD), IDIR can lookup self as well
- [ ] IDIR lookup Business BCeID by userID  (scenario 4.1a, 4.1b is enabled in TEST and PROD)
- [ ] Business BCeID lookup BCeID by userID (scenario 1.3a, 1.3b is enabled in TEST and PROD)
![Image](https://github.com/bcgov/nr-forests-access-management/assets/23131735/b60ee30c-e05d-4f57-8b9b-1cc8db60cd23)
**Note TODO: ask IDIM team why Business BCeID lookup self is not returning the business_guid and email information**  

![Image](https://github.com/bcgov/nr-forests-access-management/assets/23131735/9493ac8e-56f2-45d4-a873-73f85c05f290)




Backend:
- [ ] IDIR lookup IDIR by userID  (scenario 4.3a, 4.3b is enabled in TEST and PROD), IDIR can lookup self as well
- [ ] IDIR lookup Business BCeID by userGuid  (scenario 4.1a, 4.1b is enabled in TEST and PROD)
**TODO:  why no email returned for PROD env?**
![Image](https://github.com/bcgov/nr-forests-access-management/assets/23131735/e331277d-6a79-49dd-a822-02ed3f141789)
- [ ] Business BCeID lookup BCeID by userGuid (scenario 1.3a, 1.3b is enabled in PROD)
![Image](https://github.com/bcgov/nr-forests-access-management/assets/23131735/f2807cae-f269-4fec-ba66-ebfa40108d1d)
**TODO: this is not enabled in TEST**
![Image](https://github.com/bcgov/nr-forests-access-management/assets/23131735/f2b6ce48-1803-4a53-8e5f-5c3dee264656)

**Comment by MCatherine1994** [comment]
TODO summary:

- ask IDIM team why Business BCeID lookup self is not returning the business_guid and email information 
- why no email returned for PROD env when "IDIR lookup Business BCeID by userGuid"
- Business BCeID lookup BCeID by userGuid is not enabled in TEST env
