### ISSUE TITLE
FAM Role Assignment -Frontend

### ISSUE THREAD

**Issue by gormless87** [bcgov/nr-forests-access-management#143]
**As a** *an application access administrator* **I want** *to add users to an application and a role* **So That** *(they can access the application*

**Additional Context**
-- Users added by a known BCeID or IDIR username (front-end)
-- For MVP Roles will be added to db via Flyway as there are no API endpoints for that functionality yet (fixtures)
--  A security role will exist in FAM for each FOM role. For MVP there will be a single administrative FAM role for each app that can perform all access management functions for that application (Create tickets)
-- API will validate that you have the FAM role required to perform an operation using the FAM API (Create ticket - (when a user logs in, Cognito will query the role the user has on FAM and send the JWT with the role and application).

---For Future Consideration:
-- Users added via IDIM web service to lookup by name (Not MVP; this will be developed in a later version)
-- More fine-grained permission roles

**Acceptance Criteria**
- [ ] Given I have specified a username (BCeID/IDIR) and a role, and optionally ForestClient, When I click RoleAssignment, Then if the user does not exist it gets created, if the ForestClient role does not exist it gets created, if the ForestClient record does not exist it gets created, and then the role assignment gets created
- [ ] Given the role assignement is created  When the user logs in to FAM secured application, Then assigned role appears in the jwt

**Definition of Done**
- [ ] Ready to Demo in Sprint Review
- [ ] Does what I have made have appropriate test coverage?
- [ ] Documentation and/or scientific documentation exists and can be found
- [ ] Peer Reviewed by 2 people on the team
- [ ] Manual testing of all PRs in Dev and Prod
- [ ] Merged
