### ISSUE TITLE
FAM Login User Front-End

### ISSUE THREAD

**Issue by gormless87** [bcgov/nr-forests-access-management#144]
**As a** application access manager **I want** *to login to FAM* **So That** *I can provision access for other users to my application*

**Additional Context**
-- Publicly available landing page with login button that take you to common login page
-- IDIR only
-- Authentication takes place (jwt contains UserID, ClientID)
-- Authorization takes place  (jwt contains which Applications and Roles)
-- ClientID is related to an Application and determines which apps are in the pulldown list (db query, not API call)
-- If user has no FAM roles, message appropriately
-- For each application supported by FAM, there is a role in the db called "app_admin_<application_id>". When a user logs into FAM, a list of these roles is available from the JWT. The FAM SPA parses the list of these roles to create a list of applications that the user can choose from.

**Acceptance Criteria**
- [ ] Given I have logged in successfully with an IDIR , When redirected to FAM, Then I am presented with a list of applications that I am allowed to manage
- [ ] Given I have logged in successfully with an IDIR, When thee are no applications returned, Then I am advised to check with the FAM Team

**Definition of Done**
- [ ] Ready to Demo in Sprint Review
- [ ] Does what I have made have appropriate test coverage?
- [ ] Documentation and/or scientific documentation exists and can be found
- [ ] Peer Reviewed by 2 people on the team
- [ ] Manual testing of all PRs in Dev and Prod
- [ ] Merged
