### ISSUE TITLE
IDIR username validation 

### ISSUE THREAD

**Issue by ArogeG** [bcgov/nr-forests-access-management#483]
**Describe the task**
To ensure that IDIR  records are validated with IDIM lookup tool, FAM needs to integrate with the IDIM webservices 

**Acceptance Criteria**
- [ ] Upon granting access to a user in FAM, the IDIR  should be validated against IDIM web service. 
- [ ] When record not found on Grant Access , return error

**Task**
- [ ] implement backend as validation check

**Additional context**
frontend UI design #490
technical onboarding for the integration, contact IDIM team #528
Scope restricted to grant access screen, IDIR and  Business BCeID only, no persistent storage

**Comment by MCatherine1994** [comment]
Tested in SOAP UI, searchInteralAccount method can allow us search for IDIR user by their userID(username), first name and last name. And it's case insensitive. There're options to select exact match or contains, or start with.

**Comment by MCatherine1994** [comment]
Can use the python zeep package to make the SOAP API call: https://docs.python-zeep.org/en/master/, basic auth example: https://stackoverflow.com/questions/40173217/python-soap-client-with-zeep-authentication

**Comment by basilv** [comment]
We do NOT have connectivity from our AWS environment to at least the dev web service. Tested on the AWS dev workspace bastion host:
h-4.2$ nslookup gws2.development.bceid.ca
Server:         10.12.0.2
Address:        10.12.0.2#53

Non-authoritative answer:
Name:   gws2.development.bceid.ca
Address: 142.34.252.115

sh-4.2$ traceroute https://gws2.development.bceid.ca/webservices/Client/V10/BCeIDService.asmx?WSDL
https://gws2.development.bceid.ca/webservices/Client/V10/BCeIDService.asmx?WSDL: Name or service not known
Cannot handle "host" cmdline arg `https://gws2.development.bceid.ca/webservices/Client/V10/BCeIDService.asmx?WSDL' on position 1 (argc 1)
sh-4.2$ traceroute gws2.development.bceid.ca
traceroute to gws2.development.bceid.ca (142.34.252.115), 30 hops max, 60 byte packets
 1  * * *
 2  * * *
...
6  * * *^C
sh-4.2$ curl https://gws2.development.bceid.ca/webservices/Client/V10/BCeIDService.asmx?WSDL
curl: (28) Failed to connect to gws2.development.bceid.ca port 443 after 130541 ms: Couldn't connect to server

**Comment by basilv** [comment]
Questions to ask:
1. Maybe the BCeIDService in production is accessible outside the network, and just dev is locked down?
2. Maybe the Cloud Pathfinder team has an option to enable network trust between AWS workspaces and government on-prem network

**Comment by ianliuwk1019** [comment]
Thanks to Basil's AWS network testing and Conrad's poking around with Pathfinder we know that:
- We confirm there is no access from AWS to `https://gws2.bceid.ca` domain to the IDIM webservice.
- Some team at Pathfinder did build a proxy before for the integration with service in VPN, we can possibly borrow the same idea/code from there.

Based on document section "**3.1.2	Access from outside of SPAN/BC without a 3PNG**", our service should use these webservice sits for integration:
Clients should configure their firewalls to allow outbound requests to ports 80 and 443 on the BCeID Web Services reverse proxy servers at:
![image.png](https://images.zenhubusercontent.com/62a9ff93d8506f14758ef03a/52f605ee-7a14-428c-b27a-031384022ed6)
![image.png](https://images.zenhubusercontent.com/62a9ff93d8506f14758ef03a/893bd5b4-d68e-4cb1-b9ac-d3fccb9fc560)

**Comment by basilv** [comment]
I tested with ws.bceid.ca (as the documented reverse proxy to use for external connectivity). traceroute fails from AWS, but I think that's because outgoing ping requests are disabled from AWS. I'm able to tracert from my CGI laptop mostly successfully.

curl --insecure https://ws.bceid.ca fails from CGI laptop and from AWS bastion host due to SSL failed handshake.

This statement in the developers guide may be relevant: "The server certificates are issued by an Entrust Certificate Authority.  Online Services should add the Certificate Authority to their Trusted Root Certification Authority store instead of trusting each BCeID server certificate."
(Although the guide doesn't specify how to obtain this certificate authority. ) However, checking with my personal laptop (to rule out CGI security web proxy), I have "Entrust Root Certification Authority" + 2 variations located in my Trusted Root Certification Authorities store.

**Comment by basilv** [comment]
Here's the error from the curl on AWS bastion host: curl: (35) OpenSSL/1.0.2k-fips: error:14094410:SSL routines:ssl3_read_bytes:sslv3 alert handshake failure

So my conclusion is that we do have network connectivity from the bastion host to the external reverse proxy for BCeID, but there's something weird with the certificate.

**Comment by ianliuwk1019** [comment]
A quick reference on few successful IDIM webservice calls (need **VPN - vpn2.gov.bc.ca** connection locally).
* Webservice search Request for "**User IDIR** (UserId)" -  through "**searchInternalAccount**" method:
   - This method cannot search BCEID.
```
<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:v10="http://www.bceid.ca/webservices/Client/V10/">
   <soapenv:Header/>
   <soapenv:Body>
      <v10:searchInternalAccount>
         <!--Optional:-->
         <v10:internalAccountSearchRequest>
            <!--Optional:-->
            <v10:onlineServiceId>FA10-D20F-0F7F-45B8</v10:onlineServiceId>
            <v10:requesterAccountTypeCode>Internal</v10:requesterAccountTypeCode>
            <!--Optional:-->
            <v10:requesterUserId>CMENG</v10:requesterUserId>
            <!--Optional:-->
            <v10:pagination>
               <v10:pageSizeMaximum>10</v10:pageSizeMaximum>
               <v10:pageIndex>1</v10:pageIndex>
            </v10:pagination>
            <!--Optional:-->
            <v10:sort>
               <v10:direction>Ascending</v10:direction>
               <v10:onProperty>UserId</v10:onProperty>
            </v10:sort>
            <!--Optional:-->
            <v10:accountMatch>
               <!--Optional:-->
               <v10:userId>
                  <!--Optional:-->
                  <v10:value>IANLIU</v10:value>
                  <v10:matchPropertyUsing>StartsWith</v10:matchPropertyUsing>
               </v10:userId>
            </v10:accountMatch>
         </v10:internalAccountSearchRequest>
      </v10:searchInternalAccount>
   </soapenv:Body>
</soapenv:Envelope>
```

* Webservice search Request for "**User IDIR** (UserId)" -  through "**getAccountDetail**" method:
   - Note: Based on our OSD associated profile agreement, this method (or many other methods) you can only use this **GUID** (not userId) in parameter (so we need to in advance obtain this value, probably exists in OIDC ID Token?): `<v10:requesterUserGuid>A9888E8AC6A0430E9F2200135DF625BF</v10:requesterUserGuid>`
```
<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:v10="http://www.bceid.ca/webservices/Client/V10/">
   <soapenv:Header/>
   <soapenv:Body>
      <v10:getAccountDetail>
         <!--Optional:-->
         <v10:accountDetailRequest>
            <!--Optional:-->
            <v10:onlineServiceId>FA10-D20F-0F7F-45B8</v10:onlineServiceId>
            <v10:requesterAccountTypeCode>Internal</v10:requesterAccountTypeCode>
            <!--Optional:-->
            <v10:requesterUserGuid>A9888E8AC6A0430E9F2200135DF625BF</v10:requesterUserGuid>
            <!-- v10:requesterUserId>CMENG</v10:requesterUserId -->
            <!--Optional:-->
            <v10:userId>IANLIU</v10:userId>
            <v10:accountTypeCode>Internal</v10:accountTypeCode>
         </v10:accountDetailRequest>
      </v10:getAccountDetail>
   </soapenv:Body>
</soapenv:Envelope>
```

* Webservice search Request for "**User BCEID** (UserId)" -  through "**getAccountDetail**" method:
```
<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:v10="http://www.bceid.ca/webservices/Client/V10/">
   <soapenv:Header/>
   <soapenv:Body>
      <v10:getAccountDetail>
         <!--Optional:-->
         <v10:accountDetailRequest>
            <!--Optional:-->
            <v10:onlineServiceId>FA10-D20F-0F7F-45B8</v10:onlineServiceId>
            <v10:requesterAccountTypeCode>Internal</v10:requesterAccountTypeCode>
            <!--Optional:-->
            <v10:requesterUserGuid>A9888E8AC6A0430E9F2200135DF625BF</v10:requesterUserGuid>
            <!-- v10:requesterUserId>CMENG</v10:requesterUserId -->
            <!--Optional:-->
            <v10:userId>caameng</v10:userId>
            <v10:accountTypeCode>Individual</v10:accountTypeCode>
         </v10:accountDetailRequest>
      </v10:getAccountDetail>
   </soapenv:Body>
</soapenv:Envelope>
```

* The method "**searchBCeIDAccount**" does not work for me at the moment but we probably don't need this method.

**Comment by ianliuwk1019** [comment]
Based on the BCeID Developers' guide, section "**3.1.2	Access from outside of SPAN/BC without a 3PNG**" was thought to be a possible feasible solution for integration to IDIM without VPN.

However, I did some connection tries and Basil did a very **detail network diagnosis** on all environments (IDIM proxy's dev/test/prod) connectivity, we concluded that **"DEV/TEST" proxy environments are not available (timed out)**, and **"PROD" proxy is having SSL handshake issue**: `openssl Error pointing to client certificate issue: "Verification error: unable to get local issuer certificate"` (<==from Basil's finding).

Email reply from IDIM states that:

> Why are you trying to pivot to accessing our BCeID Web Services ‘from outstide SPAN/BC without a 3PNG’?
> 
> •	In section 3.1.2, the described method requires ‘mutual authentication’ ( reverse proxy certificates ) and / or ‘restricted access based on whitelisted IP Addresses’…
> o	Please engage with your Sector Security Team ( Eric Valikoski and / or Chris Smith ) if this is something you need to set up.

and

> Be advised, the ‘Reverse Proxy’ integration with BCeID Web Services using ‘mutual authentication’ & ‘IP White Listing’ options is essentially out of favour… [ Personally, I am only aware of 1 legacy online service that is using this ‘unpopular’ integration method & nobody is using a 3PG ( that I am aware of ) for integration with BCeID or BCeID Web Services ].
> 
> •	I urge you to make the required arrangements to continue using the SPAN/BC or VPN compliant ‘regular’ BCeID Client Development environment BCeID Web Service endpoints for your BCeID Web Service call development work:
> 
> o	https://gws1.development.bceid.ca 
> o	https://gws2.development.bceid.ca 

We probably now will face difficult challenges for this integration because both options provided in developers guide are not so feasible for us from AWS. **Plus, also, the webservice does not provide "state" (or status) for both IDIR and BCEID account users which feels quite defeat the purpose for our goal for integration.** Tim points that we need to talk to "IMS | ADMS Team" for alternative:

> I do have an inquiry in to our BCeID Tier3 Technical Team on this subject, but so far it isn’t looking promising to use our ‘Client BCeID Web Services’ to successfully lookup any of the following IDIR Account ( account state ) identity attribute information:
> 
> -LockedOut 
> -AccountDisabled 
> -AccountExpired 
> 
> At this point, I will refer you to the IMS | ADMS Team ( gateway to the IDIR Team ) on the off chance they can suggest or provide an alternative ( reliable ) method of looking up the ‘current status’ of an IDIR account for your FAM online service.
> 
> •	Note to the IMS Team:  FAM is ultimately intended as an ‘Authorization Engine’ replacement for legacy ADAM | WebADE functionality for numerous online services in the NRM | NRS Sector.
> 
> o	Would the ‘MetaDIR’ ADMS service be something the FAM Team should be looking at to run a nightly ‘batch report’ on current state for existing IDIR accounts in their FAM returning user database?
> 

Out quick team discussion on this subject is, for now, favors to implement what Pathfinder team did for using "**proxy service**" in **Openshift** to access government network service (IDIM etc..) and allows FAM on AWS to access through the service before this ticket can continue. A sample code/repo can be found **[here](https://github.com/bcgov/sso-realm-registry)** (Thanks Conrad!).
@gormless87 @MCatherine1994

**Comment by ianliuwk1019** [comment]
There is an epic created for temp solution going forward: https://github.com/bcgov/nr-fom/pull/370.
This ticket will need to be refine slightly as most of the integration will be there at #370 and FAM backend will only call this new temp proxy (REST call, not SOAP webservice call) from AWS(or local) to do the business validation.
@gormless87

**Comment by MCatherine1994** [comment]
create a request ticket to get in touch with the IMS team: https://apps.nrs.gov.bc.ca/int/jira/servicedesk/customer/portal/1/SD-76213, waiting the service desk to create iStore consulting ticket for us

**Comment by gormless87** [comment]
Superceded by #679
