### ISSUE TITLE
FAM: Manage application roles

### ISSUE THREAD

**Issue by MCatherine1994** [bcgov/nr-forests-access-management#514]
**As a** *FAM/application administrator* **I want** *create/update application roles* **So That** *I can manage roles in my application. For our FAM team, so there is no need to do hotfix for role changes*. 

**Additional Context**
- we need a UI for this story
- we need apis for create/update roles, depends on the feature requests

**Acceptance Criteria**
- [ ] Given (Context), When (action carried out), Then (expected outcome)
- [ ] Given (Context), When (action carried out), Then (expected outcome)

**Definition of Done**
- [ ] Ready to Demo in Sprint Review
- [ ] Does what I have made have appropriate test coverage?
- [ ] Documentation and/or scientific documentation exists and can be found
- [ ] Peer Reviewed by 2 people on the team
- [ ] Manual testing of all PRs in Dev and Prod
- [ ] Merged
